title: Jules Baudrin # name of the site
author: Jules Baudrin # name of site's author
email: jules[dot]baudrin[at]uvsq[dot]fr # email of site's author
url:  # root address of the site
description: > # description of the site (multiple lines allowed)
  Associate professor in computer science at UVSQ, Versailles, France
favicon: "./assets/img/logo.png" # relative path to site's favicon
theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
theme_config:
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

plugins:
  - jekyll-target-blank